FROM zyuxuan0115/llvm-17:latest as llvm

FROM ubuntu:bionic as builder

RUN apt-get update \
  && apt-get install -y build-essential curl zlib1g-dev \
  && apt-get install -y ca-certificates pkg-config libssl-dev libcurl4-openssl-dev 

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y 
ENV CARGO_TARGET_DIR=/home/rust/target
ENV PATH="/root/.cargo/bin:${PATH}"
RUN rustup default 1.76

# copy clang and llvm opt 
COPY --from=llvm /llvm /llvm

ENV PATH="/llvm/bin:${PATH}"

# Copy all the sources
WORKDIR /home/rust
COPY caller ./caller
COPY callee ./callee
COPY OpenFaaSRPC ./OpenFaaSRPC
COPY DbInterface ./DbInterface
COPY merge.sh ./merge.sh 

# build function.o
RUN ./merge.sh merge caller callee && /bin/bash -c "source /root/.bashrc"
RUN ./merge.sh clean caller callee && rm -rf /llvm
