FROM ghcr.io/openfaas/of-watchdog:0.9.11 as watchdog
FROM zyuxuan0115/deathstartbench-caller-tmp:latest as obj
FROM ubuntu:bionic as final

RUN apt-get update \
  && apt-get install -y build-essential curl zlib1g-dev \
  && apt-get install -y ca-certificates pkg-config libssl-dev libcurl4-openssl-dev \
  && addgroup --system app && adduser -system app

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y 

ENV USER=app
ENV PATH=$PATH:/home/app

# Copy of-watchdog binary
COPY --from=watchdog /fwatchdog /usr/bin/fwatchdog

WORKDIR /home/app
COPY --from=obj /home/rust /home/app
RUN ./merge.sh link

ENV fprocess="function"

HEALTHCHECK --interval=3s CMD [ -e /tmp/.lock ] || exit 1

CMD ["fwatchdog"] 
