FROM ghcr.io/openfaas/of-watchdog:0.9.11 as watchdog

FROM llvm-17:latest as builder

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y 

ENV PATH="/llvm/build/bin:${PATH}"
ENV PATH="/root/.cargo/bin:${PATH}"

WORKDIR /home/rust

# Copy all the sources
COPY function ./function
COPY OpenFaaSRPC ./OpenFaaSRPC
COPY DbInterface ./DbInterface
 
#ENV CARGO_TARGET_DIR=/home/rust/target
WORKDIR /home/rust/function
RUN cargo build 

ENV USER=app
ENV PATH=$PATH:/home/rust/function/target/debug
# Copy of-watchdog binary
COPY --from=watchdog /fwatchdog /usr/bin/fwatchdog

WORKDIR /home/app

ENV fprocess="ReadPosts"

HEALTHCHECK --interval=3s CMD [ -e /tmp/.lock ] || exit 1

CMD ["fwatchdog"] 
