apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: fission-webhook
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZjakNDQTFxZ0F3SUJBZ0lVYWhYVEF2MDM4T3Z3MUw1VmpzYVV1ZTAzZUhRd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0x6RXRNQ3NHQTFVRUF3d2tabWx6YzJsdmJpMTNaV0pvYjI5ckxtWnBjM05wYjI0dFpuVnVZM1JwYjI0dQpjM1pqTUI0WERUSTFNRE15TlRBek5EYzBNRm9YRFRJMk1ETXlOVEF6TkRjME1Gb3dMekV0TUNzR0ExVUVBd3drClptbHpjMmx2YmkxM1pXSm9iMjlyTG1acGMzTnBiMjR0Wm5WdVkzUnBiMjR1YzNaak1JSUNJakFOQmdrcWhraUcKOXcwQkFRRUZBQU9DQWc4QU1JSUNDZ0tDQWdFQXRCQlRPVHh5WGJnMmh4dUM1Y2JseFZBeHFXQlRmRDJWZmtKYwppcDg1YTFucUdnMEpjYkhjUmdvNDJBUVgzemZGRXNoN0FBRmZyaXpDb2xBRW93SmoxOG5tWlROMjNuUDlCd2ROCmM3TkFuVDUzSlRHSmlVUmczZHo0RkhTcnNFUEgzaktZcHRQNjZYY3c4Yk1ZY3NSeU11d1BSVWVkUkZnMUVGYi8KbElIUldpWlVFdkIzemhZUXJyd1FEaUdzSzNKZnRMc1R5RlljS2ZCc0Z4SWpNM2YyaHVRczVGcnlTMzJ3VlhpNgoyd09DalZQd1JxK01CQXB4eXIvWDJ6OVk1S2FPbjV2Q0xVOGw0Mlg5OHB2dldvamdJWlFhRWlnRzA3NlpLTzBGCjhGcDJOL1Q5UDRQaVJLeUN1d0s4TTd2d2w5NUg1TUExRzM0UWM5cHkrclVGbUl4OG9ZYkkyNkthMjMzQWZwRnUKT3BaWDhheGc1SEMwQ21GeXBmR3dtUE5oLzJpNm1hWDNGcldMa2p0RkhvUXlKc1VMU0cyczJLbm94OWhkU2ZKLwpaZmVNYnM4NXRRNU5BZ3NnMFlIQWZvaWJGUUJ6WC85MW1SMmkwY2ZZNEQveWF5QWlwMG1RcC9XN0ZRajhUNXl0CjdZUkY0YXpXZjg2bnFhWnZZcThJcjFLOWo4OFdBNTFOYlVLV09Va2UwUUdUeDhtTVY5cUJQYzRFSU1NWXk1b2gKbEt2STJXaFNhNzArNlFXRXRRQ05MOEU3M2ExSFpSMzczQUJjSnhyN2gvUldMTWFKaXVqclIySmN4S05tVllvSgpnTEV6YThGRFNjdXVXWEsyY0NDY3hEOG9jUVliRmRFU1hoWDhLaDAybk85TmY5Z0RscFlCanVERFZSRkhubXBZCnQxb2xyQ3NDQXdFQUFhT0JoVENCZ2pBZEJnTlZIUTRFRmdRVWl6WThIcXJlWkowS0szSEVHVWpyNW5FUk5CMHcKSHdZRFZSMGpCQmd3Rm9BVWl6WThIcXJlWkowS0szSEVHVWpyNW5FUk5CMHdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekF2QmdOVkhSRUVLREFtZ2lSbWFYTnphVzl1TFhkbFltaHZiMnN1Wm1semMybHZiaTFtZFc1amRHbHZiaTV6CmRtTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnSUJBQ1hKaUlCZzEzRS9uaU1Rd3M1eEYrQm5pUkR4L1N2V1czQlIKRlBsR0REMUxRSjRPMVZSV00vTkcwWVN0NytsaWZTZDltbGZRRW5iNWpnS2lMek1mNVUvZWp3RXBnT2Z5ME1CbwpSVjF6ald4dTY5L0MyL2krbXBabkZZSkJpYjdmT1JKSnkvd2ZCNlNOTHY0ejU5U213UE5xQ0paMlFSaXppbVBrCkxucEdtYU5salB1UW9NRThKeWlGNk8xd21WRzZIMVJOVytuVzJxRTl1NStRZUNGalhsbHE2M2M0UG9saXhQejEKbnVPUjNVamlHQWRLRXBwRHBCbG5DcWp4enpXaUVpblB0SFdYWHFudWZsdTFicFJYNU1VRVcya3BEak9mZ09KeQprRE9wcjE2WmJZbHFhS1ZsQ0JGM0M3Y0pPWWgxeFJrL2QzdC9ETzRYUStkR0lZWE14UGpWbjQ4M3VzTGtOWnFBCk9HeE9wWklJZGtEVlYwZDJqamE2dFNBb2ZxWnRsUVhhR1Bydjd2UEJGOFU3TStIdEM3ZlkrTjYzdXhYUmpyWksKKzE5ZnczdGR3REZiQWVTek9GSkt6YmpkVitqVi9WZkc2QlZSaFVGM2hQWXl3QnpHU0hKdURmZXNqcTRHV2pPMgpIMkFuNitnclhUOW54OGo5SFovMU5Fc0hlVWJTNmdLSzhiMHo3Q1pyMnVrUG1aT2N0U3BBMDlGeXYwaStpRk1YCjhzVG9FRng3ZmJ0bk1KdjFVTS9TcXNEdDJOYlRxRnJQUHlsMDBpd2VLb0RCay9uODVwdnlTc24zOHdJNUNkVmUKUlREM0NZYjZLZUFkQmNreU9ENW9YZ1d5T2FkSVJOSm1kVDdQSXVOVno4NVR2QzJCeTJjTlNndHNaVTBiT0c1QgpRZngxWUN6WgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: fission-webhook
      namespace: fission-function
      path: /mutate
  failurePolicy: Fail
  name: fission-webhook.fission-function.svc
  rules:
  - apiGroups:
    - ''
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
    scope: '*'
  sideEffects: None
  timeoutSeconds: 5
