apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: fission-webhook
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZjakNDQTFxZ0F3SUJBZ0lVSW9RNWZ1YTB5RTNRWmJOVWV4VTFDOEdIbldvd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0x6RXRNQ3NHQTFVRUF3d2tabWx6YzJsdmJpMTNaV0pvYjI5ckxtWnBjM05wYjI0dFpuVnVZM1JwYjI0dQpjM1pqTUI0WERUSTFNRFF3TkRBeE5UUXpORm9YRFRJMk1EUXdOREF4TlRRek5Gb3dMekV0TUNzR0ExVUVBd3drClptbHpjMmx2YmkxM1pXSm9iMjlyTG1acGMzTnBiMjR0Wm5WdVkzUnBiMjR1YzNaak1JSUNJakFOQmdrcWhraUcKOXcwQkFRRUZBQU9DQWc4QU1JSUNDZ0tDQWdFQXJFNmNyY0lrQVVZR3RuQWVHYzg3WUNJMGtRdEw1ZFZsSGx1RAp5ek9QVXNVL2k2NXZ6YWt4M1ZidWprTW92TVFDQisvMHYvKzRiRXdUbHU3c1AyWTQ4dmFHZ29KcWg4MmNNU3pLCmNOV29GUytreFppQkUreDB2dnU5bTRVOTVTSGcrM3FoRVlTNy9jTng1UFpCVDN3S1BFYmFHMnJyb1g3WXVKc3oKSjFtSS9HMitWY0l3bkRjR3V3U0xjdkJLM0JQcEU0bVNpRmlwd08zWnFLQXlUeHlCQ1RaWjJiY2g5anJ5NUJrTwo2eS9SbGY5T1c4all4cVlMZE9xRTcwenE4RzVNVjg3WC8xRFExUGVWT1lXL2YxZXFuSDM2UU1GbjBoSlc2MGZ4CkFoSW41Y3V6SlZqeG5xZExkR0FKT0VlVDhxbEJpYStzTldLZkVXcllQdldOcWxwdFBXSXF3TWZ4VlBOT3J6OFYKWisrT3NKckgvekpQbElkUndISmlyWEM1bUI3eGUraEY2NHcxTkg1UWU1b0xoaitqZUVEWXZUd0UxR1hEb3ZKUgp4TlRycklSTDg2YVBWejBDMkpvTUlwMzJrR0ZlZXNYZlRjRk9LR3BqbHVKd09yK1FDYW9NMEp1SENXVWl1N3NZClhUODZaMTVBVFJ2RDlmODgxTVk4L3FlaGxDdzlqM0xkOHNTbFdEMDEwMWcwUi8wMGtZU2hjSTdha21ETWVIVVEKb0pSaFZ2K1dRRTcvejNpMklFUWV0Y09xdlIyNERLOHV1TG80KzgyQXBTRTUwdXJQeEJ3ZTBmSHNpVjlGWC9vVgphcmZxMlAvSTJhVU5xQWdXbnhwbHNrOHM0UWw0V3M0NnFSb09QZkNDc1htSDNHci9jRGIvVVM4UzdBVldlcDBiCkI3ZmdDSnNDQXdFQUFhT0JoVENCZ2pBZEJnTlZIUTRFRmdRVXBBQ05FTnVhQzNSbFQ5ZW1Wb3FnblJMRnFDUXcKSHdZRFZSMGpCQmd3Rm9BVXBBQ05FTnVhQzNSbFQ5ZW1Wb3FnblJMRnFDUXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekF2QmdOVkhSRUVLREFtZ2lSbWFYTnphVzl1TFhkbFltaHZiMnN1Wm1semMybHZiaTFtZFc1amRHbHZiaTV6CmRtTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnSUJBR2FRNWpvdGpRRm5XQTBobXdVakhOcG0xLzJYbmZPYk1YdmUKRzdCc3ppSE9LM0tqYW9nSVk2dWZueVZBSHltODBCTVhmVGVqL0xBSkFjd3FlK1JKcE9sTEhSVEpDMzUxWmN5LwplcVVpRDVhZDhVcjFhZWc5SmlleUNsSXV5SlBRaGR5bC9aMi9UZVlEVHgzNVM5Q0QwUUI1Y0Ira0FqcXkrdUxjCjJSOW5Hekp3L2FHd1RIdWdIWkdYRXdrMEpnUWtxS1JCbytOQkVFWjE4Y2dESWtMSlltek9WdXZMc054S3REY00KMWc3MC9icytTQ2kvUk84cFQ0ejdEWSsvTWNiais1TndwVXNrTUFSZDZ0S2UzdVdidU1SZURsNGRVa3NmMDFJWQpOMFMxK0dMTHVyclhFWDAvT2hPZHU2c0ZaYUpZbDJRbnBFMWpoY2tFT3Y4YTRMOFc4cS9JMENtdUFRdzdFcTlZCmFuSFAwQ2JYT3AwdEx5N1Zkd1FobkZNZDE2emdTazROZFk4K085MkltVWVNeUg4SWcvVUFvWFBKNllMQ2ZRcS8KK3NsMTI0T0Z4QXRJN2dnVjdWRVRXd0Z6Z2l0SlJBWms5UzZ4amxya3VhTWFMRGJoSGVwRXlpZkZwNVlpbUFOTApsNWp0WE9MalVycDdoRzk4UXVoRXhETSt4MW94dVpna2g0ZSttOGVIcHI4bDc1R1BJWHZBMW82K0FJdktJSjJpCklZcGFZVExCSW13Q2x3U2Y4ZmEveGJQL3NDeGVKazloVlRLcE5GNksra3h5cU9kbitNeFFnMDJoMXczeUVhK3YKbldCUmxVeG8xV2RaYjdOT1lYMUNVd2FJM0R0Mk92VzZqeTBScmV4NytsOHFXeUVqVHpvblpWQVE2OEpJSlFqTwpqa1I5anZmLwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: fission-webhook
      namespace: fission-function
      path: /mutate
  failurePolicy: Fail
  name: fission-webhook.fission-function.svc
  rules:
  - apiGroups:
    - ''
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
    scope: '*'
  sideEffects: None
  timeoutSeconds: 5
