apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadvisor
  namespace: cadvisor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cadvisor
  template:
    metadata:
      labels:
        app: cadvisor
    spec:
      containers:
      - args:
        - --storage_driver=influxdb
        - --storage_driver_db=cadvisor
        - --storage_driver_host=http://influxdb.influxdb.svc.cluster.local:8086
        - --storage_driver_user=root
        - --storage_driver_password=root
        - --housekeeping_interval=100ms
        image: gcr.io/cadvisor/cadvisor:latest
        name: cadvisor
        ports:
        - containerPort: 8080
