FROM zyuxuan0115/rust-env as builder
# Copy all the sources
COPY function ./function
COPY OpenWhiskRPC ./OpenFaaSRPC
COPY DbInterface_wsk ./DbInterface
 
WORKDIR /home/rust/function
RUN cargo build --release 
