FROM --platform=${TARGETPLATFORM:-linux/amd64} ghcr.io/openfaas/classic-watchdog:0.2.3 as watchdog
FROM --platform=${TARGETPLATFORM:-linux/amd64} python:2.7-alpine

ARG TARGETPLATFORM
ARG BUILDPLATFORM

# Allows you to add additional packages via build-arg
ARG ADDITIONAL_PACKAGE="g++ wget git make curl curl-dev"

COPY --from=watchdog /fwatchdog /usr/bin/fwatchdog
RUN chmod +x /usr/bin/fwatchdog
RUN apk --no-cache add ca-certificates ${ADDITIONAL_PACKAGE}

# Add non root user
RUN addgroup -S app && adduser app -S -G app

#ARG BUILD_DEPS="ca-certificates g++ wget git libboost-all-dev libevent-dev libssl-dev libtool make curl"
#RUN apt-get update \
#  && apt-get install -y build-essential \
#  && apt-get install -y ${BUILD_DEPS} --no-install-recommends

WORKDIR /home/app/

COPY caller.c   .
COPY Makefile   .

RUN make

RUN chown -R app /home/app && \
  mkdir -p /home/app/python && chown -R app /home/app
USER app
ENV PATH=$PATH:/home/app/.local/bin:/home/app
#ENV PYTHONPATH=$PYTHONPATH:/home/app/python

RUN mkdir -p function

WORKDIR /home/app/



# Allow any user-id for OpenShift users.
RUN chown -R app:app ./ && \
  chmod -R 777 /home/app/python

USER app

ENV fprocess="caller"
EXPOSE 8080

HEALTHCHECK --interval=3s CMD [ -e /tmp/.lock ] || exit 1

CMD ["fwatchdog"]
